package com.gatto.interactiondelay.interaction;

public enum InteractionCategory {
	BLOCK_PLACEMENT,
	OBSIDIAN_PLACE,
	ENDER_PEARL,
	WIND_CHARGE,
	END_CRYSTAL,
	FIREWORK,
	CHORUS_FRUIT,
	XP_BOTTLE,
	SPLASH_POTION,
	RESPAWN_ANCHOR_PLACE,
	GLOWSTONE_CHARGE,
	ANCHOR_EXPLODE,
	ARMOR,
	ELYTRA,
	OTHER_ITEM,
	BLOCK_INTERACTION
}
